FROM rust:1.82-bookworm

WORKDIR /app

RUN cargo install cargo-watch sqlx-cli --no-default-features --features rustls,postgres

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build
RUN rm -rf src

COPY src/ src/
COPY migrations/ migrations/

ENV SQLX_OFFLINE=true

EXPOSE 8080

CMD ["cargo", "watch", "-x", "run"]
